### ISSUE TITLE
Why is yocto BSP compatible with scarthgap but actually using styhead poky and meta-oe

### ISSUE THREAD

**Issue by ycardaillac** [phytec/meta-ampliphy#3]
Hi,

As you know from my previous tickets I'm working on upgrading our BSP based on phytec's to scarthgap. However I've just realized that what we are actually working with is a styhead BSP.

poky is compatible with styhead and so does meta-openembedded, why is that?

poky/meta/conf/layer.conf: LAYERSERIES_COMPAT_core = "styhead"
meta-openembedded/meta-oe/conf/layer.conf: LAYERSERIES_COMPAT_openembedded-layer = "styhead"

that's taken from the bsp BSP-Yocto-Ampliphy-i.MX8MM-master which is supposed to be in scarthgap right?

 Are you not planning to release a mainline scarthgap BSP, which is the LTS version?

**Comment by smk-embedded** [comment]
Scarthgap mainline BSP is only supported on Pollux with phyCORE-i.MX8M Plus. To support 8MM is currently not planned. You can try to get it running and we will try to help.
Plan for 8MM is currently to release a scarthgap BSP based on the IMX vendor stack.

**Comment by smk-embedded** [comment]
Sadly, 8MM BSP release has been postponed several times, now development is in progress and latest scarthgap NXP release will be finished around end of march. Ih hope you got everything working for your project! I will close this thread for now. If you have specific issues, please open a new issue.
